version: '3'

networks:
  yakforms-net:
    driver: bridge

name: yakforms

services:
  yakforms-web:
    image: nginx:1.25-alpine
    depends_on:
      - yakforms-app
    volumes:
      - app-data:/var/www/html:ro
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./theme:/var/www/html/profiles/yakforms_profile/themes/yaktheme_ltr:ro
      - ./modules:/var/www/html/sites/all/modules:ro
      - ./libraries:/var/www/html/sites/all/libraries:ro
    ports:
      - "127.0.0.1:8787:80"
    networks:
      - yakforms-net
    container_name: yakforms-web
  yakforms-app:
    image: unillett/yakforms:latest
    build:
      context: ./
      dockerfile: ./app.dockerfile
    env_file:
      - .env
    depends_on:
      - yakforms-postgres
    volumes:
      - app-data:/var/www/html
      - ./modules:/var/www/html/sites/all/modules/
      - ./libraries:/var/www/html/sites/all/libraries/
      - ./theme:/var/www/html/profiles/yakforms_profile/themes/yaktheme_ltr/
    networks:
      - yakforms-net
    container_name: yakforms-app
  yakforms-postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - "127.0.0.1:5454:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - yakforms-net
    container_name: yakforms-postgres

volumes:
  app-data:
  postgres-data:
