version: '3'
services:
  proxy:
    image: nginx:alpine
    depends_on:
      - yakforms
    volumes:
      - ./conf/nginx/nginx_default.conf:/etc/nginx/conf.d/default.conf:ro
      - yakforms:/var/www/html:ro
    ports:
      - 80:80

  yakforms:
    image: nouts/yakforms:${YAKFORMS_VERSION}-fpm
    depends_on:
      - db
    volumes:
      - yakforms:/var/www/html

  db:
    image: postgres:13-alpine
    env_file:
      - .env

volumes:
  yakforms: